apiVersion: v1
kind: Service
metadata:
  name: spring-service
  namespace: devops
spec:
  selector:
    app: spring-app
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 30080
  type: NodePort
